language: python

python:
  - 3.4

cache:
  apt: true
  directories:
    - capnproto
    - zeromq4-1-master

env:
  - TESTENV=py34 CC=gcc-4.9 CXX=g++-4.9

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install $CXX $CC
  - ./install_zeromq41.sh

install:
  - git submodule update --init
  - if [[ ! -e capnproto ]]; then git clone --depth=1 --single-branch -b release-0.5.1 https://github.com/kentonv/capnproto.git; fi
  - cd capnproto/c++
  - if [[ ! -e capnp ]]; then autoreconf -i && ./configure && make -j5 && sudo make install; fi
  - cd ../../
  - pip install tox coveralls
  - pip install -e .

script:
  - tox -e $TESTENV

after_success:
  - coveralls
