language: python

python:
  - 3.4

cache:
  apt: true
  directories:
    - capnproto
    - zeromq4-1-master

env:
  - TESTENV=py34 CC=gcc-4.9 CXX=g++-4.9

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install $CXX $CC
  - ./install_zeromq41.sh
  - ./install_capnp051.sh

install:
  - git submodule update --init
  - pip install tox coveralls
  - pip install -e .

script:
  - tox -e $TESTENV

after_success:
  - coveralls
