language: python

cache:
  pip: true
  apt: true
  directories:
    - capnproto


env:
  - TESTENV=py34 GCC_VER=4.9 CC=gcc-4.9 CXX=g++-4.9

install:
  - git submodule update --init
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install g++-$GCC_VER gcc-$GCC_VER
  - if [[ ! -e capnproto ]]; then git clone --depth=1 --single-branch -b release-0.5.1 https://github.com/kentonv/capnproto.git; fi
  - cd capnproto/c++
  - if [[ ! -e capnp ]]; then autoreconf -i && CC=gcc-$GCC_VER CXX=g++-$GCC_VER ./configure && make -j5 && sudo make install; fi
  - cd ../../
  - pip install tox
  - pip install -e .

script:
  - tox -e $TESTENV
