site_name: Cara
pages:
  - [index.md, Home]
  - [differentiations.md, Differentiations]
  - [structs.md, Structs]
  - [interfaces.md, Interfaces]
  - [remote.md, Interfaces on the Wire]
  - [advanced_usage.md, Advanced Usage]
  - [changelog.md, Changelog]
theme: readthedocs

site_url: http://cara.readthedocs.org/en/latest/
repo_url: https://github.com/chainreactionmfg/cara
repo_name: 'GitHub'
site_description: "cara is a Cap'n Alternative RPC API"
site_author: "Fahrzin Hemmati, Chain Reaction Mfg"
copyright: "2015, Fahrzin Hemmati, Chain Reaction Mfg"
